### ISSUE TITLE
Checklist for R.kt #3

### ISSUE THREAD

**Issue by shiraji** [shiraji/to-done#2]
- [x] Use newest slide
- [x] Hide Dock (Right click dock and "Turn hiding on"
- [x] Do not disturb mode (Click top right corner)
- [x] Clear desktop icons (`defaults write com.apple.finder CreateDesktop -boolean false; killall Finder`)
- [x] Open https://youtrack.jetbrains.com/issue/KT-20357
- [x] Open https://github.com/shiraji/kotlin
- [ ] Open Intellij + Regexps.kt
